### ISSUE TITLE
IPv6 support for existing built-in servers

### ISSUE THREAD

**Issue by curlymon** [turbobytes/dnsperfbench#1]
I see you accept IPv6 addresses via command line which is exciting to see! However it seems your built-in ip addresses only list the IPv4 variants of each service. It would be nice to have the IPv6 variants to compare and contrast alongside the current addresses.

**Comment by sajal** [comment]
Great idea. 
I will do some tests to check if they have any negative performance for non-IPv6 compatible users, if so then put it behind a flag.
